[package]
name = "bovido"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.5.0", features = ["dynamic"] } 
heron = { version = "0.11.0", features = ["2d", "debug-2d"] }
